sudo: required
language: generic

services:
  - docker

after_success:
  - docker build -t george7a/multi-client ./client
  - docker build -t george7a/multi-nginx ./nginx
  - docker build -t george7a/multi-server ./server
  - docker build -t george7a/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push george7a/multi-client
  - docker push george7a/multi-nginx
  - docker push george7a/multi-server
  - docker push george7a/multi-worker
